name: qr_scanner
description: "Offline-First QR/Barcode Scanner"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Scanning
  mobile_scanner: ^7.1.4
  google_mlkit_barcode_scanning: ^0.12.0

  # Storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.1
  path: ^1.8.0

  # State Management
  provider: ^6.1.1

  # UI
  url_launcher: ^6.3.0
  share_plus: ^12.0.0

  # Location
  geolocator: ^14.0.0
  geocoding: ^4.0.0

  # Image
  flutter_image_compress: ^2.1.0
  image_picker: ^1.0.4
  image: ^4.3.0
  gal: ^2.3.0

  # Audio
  audioplayers: ^6.5.0

  # Utils
  intl: ^0.20.0
  permission_handler: ^12.0.0

  # QR Generation
  qr_flutter: ^4.1.0
  font_awesome_flutter: ^10.7.0

  # Ads
  google_mobile_ads: ^7.0.0

  # Charts
  fl_chart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/Gemini_Generated_Image_i99qp2i99qp2i99q (2).png"
  adaptive_icon_foreground: "assets/Gemini_Generated_Image_i99qp2i99qp2i99q (2).png"
  adaptive_icon_background: "#0a0a1a"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
